
services:
  resilience-app:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - sre-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - sre-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - sre-network

networks:
  sre-network:
    driver: bridge
