name: Build and Push
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Push Container
        run: |
          echo "Building container image..."
          # Aqui adicionaremos futuramente o comando de build (ex: docker build)
